[tool.poetry]
name = "hog_apitest"
version = "0.1.0"
description = ""
authors = ["susu <31542614@qq.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
